config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: "users#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  scope "/" do
    resources :users do
      resources :posts do
        resources :comments, only: [:create, :destroy]
        resources :likes, only: [:create]
      end
    end
    namespace :api, defaults: { format: :json } do
      resources :sessions
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end  
end

app/views/partials/_comments_list.html.erb
<div class='p_comments'>
  <% if comments.empty? || comments.nil? %>
    <span class='comment_item'><%= "No comment yet" %></span>
  <% else %>
    <ul class='list'>
      <% comments.each_with_index do |comment, index| %>
        <li class='comment_item'>
          <%= comment.author.name %>: <%= comment.text %>
          <%if can? :delete, comment%>
            <%= button_to "Delete comment",
              [comment.post.author, comment.post, comment], 
              method: :delete,
              class:"btn btn-outline-danger btn-del-comment"
           %>
          <%end%>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/partials/_errors.html.erb
<% if errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(errors.count, "error") %> prohibited this action from being completed:</h2>

    <ul>
    <% errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
   <%= link_to "Home", users_path %> 
   <%= button_to "Sign out", destroy_user_session_path, method: :delete%>
</nav>

app/views/partials/_post_item.html.erb
<div class='u_post_item'>
  <h4 class='u_post_title'>
    <%= link_to user_post_path(post.author,post) do %>
      <%=index + 1%>: <%=post.title%>
    <%end%>

  </h4>
  <div class='u_post_details'>
    <div class='u_post_text'>
      <%=post.text%>
    </div>
    <div class='u_post_reactions'>
      <span>Comment: <%=post.comments_counter%>, </span>
      <span>Like: <%=post.likes_counter%> </span>
    </div>
  </div>
</div>

app/views/partials/_user_profil.html.erb
<div class='user_item'>
  <div class='user_img'>
    <%profil = nil%>
    <%if user.photo.present?%>
      <%profil = user.photo%>
    <%else%>
      <%profil = "https://picsum.photos/200"%>
    <%end%>
    <%= image_tag profil, 
                alt: "profil image", width: "100px", height: "100px", class:'profile_picture' %>
  </div>
  <div class='user_details'>
    <p class='u_details_name'>
     <%= link_to user_path(user) do %>
      <%= user.name %><br>
      <%end%>
    </p>
    <span class='u_details_numberOfPosts'>
      Number of posts: <%= user.posts_counter%>
    </span>
  </div>
</div>