config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: "users#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  scope "/" do
    resources :users do
      resources :posts do
        resources :comments, only: [:create, :destroy]
        resources :likes, only: [:create]
      end
    end
    namespace :api, defaults: { format: :json } do
      resources :sessions
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'

  def admin?
    role == 'admin'
  end

  def three_recent_posts
    Post.where(author: id).limit(3).order(created_at: :desc)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @current_user = current_user
    @posts = @user.posts
  end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/views/users/index.html.erb
<h1>Users</h1>
<div>
    <ul id='users_list'>
        <% @users.each do |user| %>
    <li>
         <%= render partial: "partials/user_profil", locals: { user: user } %>
    </li>
    <% end %>
</ul>
</div>

app/views/users/show.html.erb
<h1>Show a user</h1>
<div class='user_profil'>
    <%= render partial: "partials/user_profil", locals: { user: @user } %>
    <div class='user_bio'>
    <h3>Bio: <h3>
        <%=@user.bio%>
    </div>
    <%# to ensure that only the current user can create a post %>
    <%= link_to 'Add Post', new_user_post_path(@current_user) %>
    <div class='user_posts'>
        <ul id='users_list'>
            <% @user.three_recent_posts.each_with_index do |post, index| %>
                <li>
                    <%= render partial: "partials/post_item", locals: { post: post, index:index } %>
                </li>
            <% end %>
        </ul>
    </div>
    <%= link_to 'See all posts', user_posts_path(@user.id), method: :get, class: 'btn btn-primary'%>
</div>