config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: "users#index", as: :authenticated_root
    end

    unauthenticated do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  scope "/" do
    resources :users do
      resources :posts do
        resources :comments, only: [:create, :destroy]
        resources :likes, only: [:create]
      end
    end
    namespace :api, defaults: { format: :json } do
      resources :sessions
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
  end  
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { in: 2..250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_counter_post

  def five_recents_comments
    Comment.where(post_id: id).limit(5).order(created_at: :desc)
  end

  private

  def update_counter_post
    User.increment_counter(:posts_counter, author_id)
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    before_action :set_user

    def index
      @posts = @user.posts
      render json: @posts
    end

    def show
      @post = @user.posts.find(params[:id])
      render json: @post
    end

    private

    def set_user
      @user = User.find(params[:user_id])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  def index
    @current_user = current_user
    @posts = @user.posts.includes(comments: :author)
  end

  def show
    @post = Post.find(params[:id])
    @current_user = current_user
    @comments = @post.comments
    @comment = Comment.new(author: @current_user, post: @post)
  end

  def new
    if user_signed_in?
      @user = current_user
      @post = @user.posts.new
      respond_to do |format|
        format.html { render :new, locals: { post: @post } }
      end
      puts 'created'
    else
      redirect_to new_user_session_path, alert: 'You must be logged in to create a post.'
    end
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    @post.author_id = @user.id
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = ' Post created '
          redirect_to user_post_path(@user, @post)
        else
          render :new, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    user = @post.author
    @post.destroy
    flash[:success] = ' Post deleted '
    redirect_to user_posts_path(user)
  end

  def post_params
    params.require(:post).permit(:title, :text, :author_id)
  end

  private

  def set_user
    @user = User.includes(posts: :comments).find(params[:user_id])
  end
end

app/views/posts/index.html.erb
<h1>Here is a list of posts for a given user</h1>
<%# in case we have flash %>
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>
<div class='user_profil'>
  <%= render partial: "partials/user_profil", locals: { user: @user } %>
  <div class='user_posts'>
    <%= link_to 'Add Post', new_user_post_path(@current_user.id) %>
  <%if @posts.present?%>
    <ul id='users_list'>
      <% @posts.each_with_index do |post, index| %>
        <li>
          <%= render partial: "partials/post_item", locals: { post: post, index:index } %>
          <%comments=post.five_recents_comments%>
          <%if can? :delete, post%>
            <%= button_to "Delete post", 
              user_post_path(post.author, post), 
              method: :delete,
              class:"btn btn-outline-danger btn-del-post"
            %>
          <%end%>
          <%= render partial: "partials/comments_list", locals: { comments: comments} %>
        </li>
      <% end %>
    </ul>
  <%else%>
    <%='No post'%>
  <%end%>
  </div>
  <button id='pagination'>Pagination</button>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= form_with model: @post, url: user_posts_path(@user), method: :post, local: true do |f| %>
  <div>
    <%= f.label :title%><br>
    <%= f.text_field :title%>
  </div>
  <div>
    <%= f.label :text%><br>
    <%= f.text_area :text%>
  </div>
  <div>
    <%=f.submit 'Post'%>
  </div>
<%end%>
<%# In case we have a error %>
<%= render partial: "partials/errors", locals: { errors: @post.errors } %>

app/views/posts/show.html.erb
<h1>Show a posta of a given user</h1>
<% # in case we have flash %>
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>
<div id="post_container">
  <div class='u_post_reactions'>
    <span>Comment: <%= @post.comments_counter %>, </span>
    <span>Like: <%= @post.likes_counter %> </span>
  </div>
  <div class="post_text">
    <h3>
      <%= @post.title %>
    </h3>
    <%= @post.text %>
  </div>
  <div id='add_like'>
    <%= button_to "Like", user_post_likes_path(@current_user.id, @post), method: :post %>
  </div>
  <div id='add_comment'>
    <%= render "comments/new" %>
  </div>
  <%if can? :delete, @post%>
    <%= button_to "Delete post",
                  user_post_path(@post.author, @post),
                
                  method: :delete,
                  class: "btn btn-outline-danger btn-del-post"
    %>
  <%end%>
  <%= render partial: "partials/comments_list", locals: { comments: @comments } %>
</div>